### ISSUE TITLE
install issue, possibly caused by genomeinfodbdata update ?

### ISSUE THREAD

**Issue by joshtburdick** [Bishop-Laboratory/RLPipes#92]
I'm having problems running RLPipes. It seemed to install and run fine on August 11.

However, now (or at least last Friday) when I install using conda 4.13.0, mamba 0.25.0, on a Ubuntu 18.04.6 LTS x86_64 machine, `RLPipes build `and `RLPipes check `run fine, but `RLPipes run` gives a string of exceptions. 

I _think_ that the relevant bit is
```
ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 74c82f26111062a9ceb3c5331088cd56:
https://bioconductor.org/packages/3.14/data/annotation/src/contrib/GenomeInfoDbData_1.2.7.tar.gz
https://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.7.tar.gz
https://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.7_src_all.tar.gz

```
My guess is that genomeinfodbdata was updated, and 1.2.7 is no longer available? (One of those URLs goes to a redirect, which presumably isn't followed by post-link.sh .)

Possibly I should just try installing RLPipes from source (I'm new to using conda/mamba in any case.)

However, this seems fairly carefully packaged, and my guess is that people who packaged it might have a better idea why this exception happening. Please reply to this if other information would be helpful for debugging.

Thank you!
Josh Burdick

**Comment by millerh1** [comment]
Hmm -- sounds like [this issue](https://github.com/bioconda/bioconda-recipes/issues/31349). The issue is not related to RLPipes per se, but with the ability of conda/mamba to solve and build the environments which depend on GenomeInfoDb.

Can you try again? The maintainers may have been delayed in updating the package on bioconda -- I just tried it and was able to successfully build each environment on my machine.

If it still does not work, then I can take a closer look and let the Bioconda team know.

**Comment by joshtburdick** [comment]
Thanks for the pointer to the other issue; it does look like an issue in the `genomeinfodb` package, which tries to download `GenomeInfoDbData_1.2.7.tar.gz` (which looks like an R package), and install it.

To try to rule out any local configuration oddity, I spun up a Ubuntu 18.04.6 LTS (on Google Cloud), and installed conda and mamba. When I tried running RLPipes, I got the error described before.

To try to narrow it down more, I created a new conda environment, and tried installing various things from `RLPipes/rlpipes/src/envs/rlseq.yaml`.
This fails with the error described before:
`mamba install --name test1 -c conda-forge -c bioconda bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_1`
However, this does work:
`mamba install --name test1 -c conda-forge -c bioconda bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2`

Various other packages from `rlseq.yaml` installed fine, including:
```
r-rcpp=1.0.9=r41h7525677_0
bioconductor-rsamtools=2.10.0=r41h619a076_1
```
So, I'm wondering if there's some web configuration difference. Possibly your web setup has a cache, which means that downloading `GenomeInfoDbData_1.2.7.tar.gz` succeeds? Puzzling.

I'll post if I figure out why it isn't working on our server.

**Comment by silvanopiazza** [comment]
Dear Dr Burdick and Dr Miller.
I have the same issue.
From what I understood some packages are tried to be downloaded from the no more active links (like depot.galaxyproject.org).
even if I comment out the bioconductor-genomeinfodbdata from the yml, other packages could not be installed:
for example:

_ERROR: post-link.sh was unable to download any of the following URLs with the md5sum f60feeafaa1b70263f960e1816aea209:
https://bioconductor.org/packages/3.14/data/experiment/src/contrib/RLHub_1.0.0.tar.gz
https://bioarchive.galaxyproject.org/RLHub_1.0.0.tar.gz
https://depot.galaxyproject.org/software/bioconductor-rlhub/bioconductor-rlhub_1.0.0_src_all.tar.gz_

BTW why all those packages are installed in the CLI version?
Do you think that is possible to have the "RLPipes run" command just to produce the peaks and the analyze them in a separate R environment?
Bests 
Silvano

**Comment by millerh1** [comment]
Thank you both for commenting! I will investigate further now and provide an update shortly.

**Comment by joshtburdick** [comment]
After a few iterations of installing packages into a test Conda environment, and seeing which one worked, I incremented the last digit of the following packages in `rlpipes/src/envs/rlseq.yaml` :
```
  - bioconductor-genomeinfodbdata=1.2.7=r41hdfd78af_2
  - bioconductor-org.hs.eg.db=3.14.0=r41hdfd78af_1
  - bioconductor-rlhub=1.0.0=r41hdfd78afI
```

It now got through the "Downloading and installing remote packages." step, and seems to be about to align files.

I'll follow-up on this post, as to whether that worked or not. (I wouldn't call it a definite fix at this point.)

**Comment by millerh1** [comment]
Thank you so much for looking into this :) It sounds like a version issue with the pinning I added to address #91 

Also I am sorry I haven't been more responsive -- I am defending my dissertation next week so things are a bit hectic. I will try to take a closer look as well in the next couple of days!

**Comment by joshtburdick** [comment]
No problem, that sounds like a pretty good reason for delays. Best of luck!

**Comment by millerh1** [comment]
Thank you!!

**Comment by millerh1** [comment]
Hi all -- my apologies for the delay. The latest commit should address these issues! Let me know if you continue finding this error and I will take another look. I will try to get this latest version updated on bioconda shortly, but you can install it using pip for now: https://github.com/Bishop-Laboratory/RLPipes#using-pip
